name: safe-her

services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: safe-her-postgres
    environment:
      POSTGRES_DB: safe-her
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - safe-her_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  safe-her_postgres_data:
